config/routes.rb
Rails.application.routes.draw do
  resources :lists
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :list
end

app/models/list.rb
class List < ApplicationRecord
    has_many :items, inverse_of: :list
    accepts_nested_attributes_for :items
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.all
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params.require(:list).permit(:title, items_attributes: [:id, :title, :price, :_destroy])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Shoppinglist
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = yield

app/views/lists/_form.html.haml
= semantic_form_for @list do |f|
  =f.inputs do
    = f.input :title

    %fieldset#items
      %legend Items
      =f.semantic_fields_for :items do |item|
        =render 'item_fields', f: item
      .links
        =link_to_add_association 'add item', f, :items

  =f.actions do
    = f.action :submit, as: :input

app/views/lists/_item_fields.html.haml
.nested-fields
    =f.inputs do
        =f.input :title
        =f.input :price
        %li
        = label_tag ''
        = link_to_remove_association 'Remove Item', f

app/views/lists/edit.html.haml
%h1 Editing list

= render 'form'

= link_to 'Show', @list
\|
= link_to 'Back', lists_path

app/views/lists/index.html.haml
%h1 Listing lists

%table
  %thead
    %tr
      %th Title
      %th item
      %th
      %th

  %tbody
    - @lists.each do |list|
      %tr
        %td= list.title
        %td= Item.all
        %td= link_to 'Show', list
        %td= link_to 'Edit', edit_list_path(list)
        %td= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New List', new_list_path

app/views/lists/new.html.haml
%h1 New list

= render 'form'

= link_to 'Back', lists_path

app/views/lists/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @list.title

= link_to 'Edit', edit_list_path(@list)
\|
= link_to 'Back', lists_path